// <auto-generated />
using System;
using ConstructIQ.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstructIQ.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915084221_AddPasswordReset")]
    partial class AddPasswordReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.BOQItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EstimatedUnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("BOQItems");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ExcessWasteRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExcessPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ExcessType")
                        .HasColumnType("int");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RecordedByUserId");

                    b.ToTable("ExcessWasteRecords");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ForecastResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GeneratedById")
                        .HasColumnType("int");

                    b.Property<int?>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ModelAccuracy")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int?>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanningWeeks")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedById");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ForecastResults");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ForecastedMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ForecastResultId")
                        .HasColumnType("int");

                    b.Property<decimal>("ForecastedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReorderSuggestion")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("Shortage")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastResultId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ForecastedMaterials");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.InventoryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ExcessQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReorderPoint")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetStockLevel")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UsedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("WastedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProjectId", "MaterialId")
                        .IsUnique();

                    b.ToTable("InventoryRecords");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.MaterialCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MaterialCategories");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.MaterialMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryRecordId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int?>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryRecordId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("RecordedByUserId");

                    b.ToTable("MaterialMovements");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ProcurementRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstimatedLeadTimeDays")
                        .HasColumnType("int");

                    b.Property<decimal>("ForecastedDemand")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("RecommendedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReorderPoint")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("SuggestedReorderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TargetStockLevel")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProcurementRecommendations");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedContractor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("SiteEngineerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("SiteEngineerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.PurchaseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedUnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalEstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("RequestedById");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.RedistributionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("AvailableExcessAtSource")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EstimatedSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAiRecommended")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("NeededQuantityAtTarget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SourceProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("SourceProjectId");

                    b.HasIndex("TargetProjectId");

                    b.ToTable("RedistributionRequests");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ActivityLog", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.BOQItem", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.Material", "Material")
                        .WithMany("BOQItems")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Phase", "Phase")
                        .WithMany("BOQItems")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Project", "Project")
                        .WithMany("BOQItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Phase");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ExcessWasteRecord", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Phase", "Phase")
                        .WithMany("ExcessWasteRecords")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Project", "Project")
                        .WithMany("ExcessWasteRecords")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.User", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Phase");

                    b.Navigation("Project");

                    b.Navigation("RecordedBy");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ForecastResult", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.User", "GeneratedBy")
                        .WithMany()
                        .HasForeignKey("GeneratedById");

                    b.HasOne("ConstructIQ.API.Models.Entities.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId");

                    b.HasOne("ConstructIQ.API.Models.Entities.Project", "Project")
                        .WithMany("ForecastResults")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedBy");

                    b.Navigation("Phase");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ForecastedMaterial", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.ForecastResult", "ForecastResult")
                        .WithMany("ForecastedMaterials")
                        .HasForeignKey("ForecastResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForecastResult");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.InventoryRecord", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.Material", "Material")
                        .WithMany("InventoryRecords")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Project", "Project")
                        .WithMany("InventoryRecords")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.Material", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.MaterialCategory", "Category")
                        .WithMany("Materials")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.MaterialMovement", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.InventoryRecord", "InventoryRecord")
                        .WithMany("MaterialMovements")
                        .HasForeignKey("InventoryRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Phase", "Phase")
                        .WithMany("MaterialMovements")
                        .HasForeignKey("PhaseId");

                    b.HasOne("ConstructIQ.API.Models.Entities.User", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryRecord");

                    b.Navigation("Phase");

                    b.Navigation("RecordedBy");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.Phase", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.Project", "Project")
                        .WithMany("Phases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ProcurementRecommendation", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Project", "Project")
                        .WithMany("ProcurementRecommendations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.Project", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.User", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.User", "SiteEngineer")
                        .WithMany()
                        .HasForeignKey("SiteEngineerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProjectManager");

                    b.Navigation("SiteEngineer");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.PurchaseRequest", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("ConstructIQ.API.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.ProcurementRecommendation", "Recommendation")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("RecommendationId");

                    b.HasOne("ConstructIQ.API.Models.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Material");

                    b.Navigation("Project");

                    b.Navigation("Recommendation");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.RedistributionRequest", b =>
                {
                    b.HasOne("ConstructIQ.API.Models.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConstructIQ.API.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConstructIQ.API.Models.Entities.Project", "SourceProject")
                        .WithMany()
                        .HasForeignKey("SourceProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructIQ.API.Models.Entities.Project", "TargetProject")
                        .WithMany()
                        .HasForeignKey("TargetProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Material");

                    b.Navigation("RequestedBy");

                    b.Navigation("SourceProject");

                    b.Navigation("TargetProject");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ForecastResult", b =>
                {
                    b.Navigation("ForecastedMaterials");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.InventoryRecord", b =>
                {
                    b.Navigation("MaterialMovements");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.Material", b =>
                {
                    b.Navigation("BOQItems");

                    b.Navigation("InventoryRecords");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.MaterialCategory", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.Phase", b =>
                {
                    b.Navigation("BOQItems");

                    b.Navigation("ExcessWasteRecords");

                    b.Navigation("MaterialMovements");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.ProcurementRecommendation", b =>
                {
                    b.Navigation("PurchaseRequests");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.Project", b =>
                {
                    b.Navigation("BOQItems");

                    b.Navigation("ExcessWasteRecords");

                    b.Navigation("ForecastResults");

                    b.Navigation("InventoryRecords");

                    b.Navigation("Phases");

                    b.Navigation("ProcurementRecommendations");
                });

            modelBuilder.Entity("ConstructIQ.API.Models.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("ManagedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
